GET http://localhost:8080/api/item?id=99
Accept: application/json

### DELETE BEITRAG
DELETE http://localhost:8080/beitragService/deleteBeitrag/1
Content-Type: application/json

###ZU KORRIGIEREN
PUT http://localhost:8080/beitragService/updateBeitrag/1
Content-Type: application/json

{
  "zahlungsart": {
    "id": 102
  },
  "zahlungsdatum": "2025-03-01",
  "beitrag": 150,
  "bezahlt": false,
  "eltern": {
    "id": 2
  }
}

### ZU KORRIGIEREN
POST http://localhost:8080/beitragService/addBeitrag
Content-Type: application/json

{
  "zahlungsdatum": "2025-01-05",
  "zahlungsart": {
    "id": 4
  },
  "bezahlt": true,
  "beitrag": 150,
  "eltern": {
    "id": 52
  },
  "faelligkeitsdatum": "2025-01-06"
}

###
GET http://localhost:8080/beitragService/getAllbeitrag
Accept: application/json

###ZAHLUNGSART
DELETE http://localhost:8080/beitragService/deleteZahlungsart/103
Content-Type: application/json

###
PUT http://localhost:8080/beitragService/updateZahlungsart/103
Content-Type: application/json

{
  "zahlungsTyp": "Paypal"
}

###
POST http://localhost:8080/beitragService/addZahlungsart
Content-Type: application/json

{
  "zahlungsTyp": "Kreditkarte"
}

###
GET http://localhost:8080/beitragService/getZahlungsart/152
Accept: application/json

###
GET http://localhost:8080/beitragService/getAllZahlungsart
Accept: application/json



###DELETE ELTERN
DELETE http://localhost:8080/eltern/deleteEltern/2
Content-Type: application/json

###UPDATE ELTERN
PUT http://localhost:8080/eltern/updateEltern/1
Content-Type: application/json

{
  "elternVorname": "Angelina",
  "elternNachname": "Atmatsidou",
  "elternEmail": "angelina@gmail.com",
  "elternTelefonnummer": "152658789652",
  "elternStrasseHausnr": "Wilmersdorferstrasse 54",
  "elternPlz": {
    "plz": "10258"
  }
}

###GET ALL ELTERN
GET http://localhost:8080/eltern/getAllEltern
Accept: application/json

###ADD ELTERN
POST http://localhost:8080/eltern/addEltern
Content-Type: application/json

{
  "elternVorname": "Jamal",
  "elternNachname": "Helle",
  "elternEmail": "jamalhelle@gmail.com",
  "elternTelefonnummer": "152658789652",
  "elternStrasseHausnr": "Charlotenburgestrasse 54",
  "elternPlz": {
    "plz": "10258"
  }
}

###DELETE KIND
DELETE http://localhost:8080/deleteKind/2
Content-Type: application/json

{}

###UPDATE KIND
PUT http://localhost:8080/updateKind/2
Content-Type: application/json

{
  "kindVorname": "Helle",
  "kindNachname": "Jamal Jr. Jr.",
  "kindGeburtsdatum": "2025-02-15",
  "besonderheiten": "kann nicht laufen",
  "gruppe": {
    "id": 1
  }
}

###GET KIND BY ID
GET http://localhost:8080/getKind/2
Accept: application/json

###GET ALL KINDER
GET http://localhost:8080/getAllKinder
Accept: application/json

###ADD KIND
POST http://localhost:8080/addKind
Content-Type: application/json

{
  "kindVorname": "Helle",
  "kindNachname": "Jamal Jr.",
  "kindGeburtsdatum": "2025-01-15",
  "besonderheiten": "gutes Baby",
  "gruppe": {
    "id": 1
  }
}

###
DELETE http://localhost:8080/standortService/deletePostleitzahl/"11123"
Content-Type: application/json

###Standort
GET http://localhost:8080/standortService/postleitzahl
Content-Type: application/json

###ADD PLZ
POST http://localhost:8080/addPostleitzahl
Content-Type: application/json;charset=UTF-8
accept: application/json

{
  "plz": "11123",
  "ort": "Berlin"
}


###ADD GRUPPE
POST http://localhost:8080/addGruppe
Content-Type: application/json

{
  "gruppeName": "Sonderblumen",
  "gruppeGroesse": 19
}

###GET ALL GRUPPEN
GET http://localhost:8080/getAllGruppe
Accept: application/json

#=======Anwesenheit=======
###ADD ANWESENHEIT
POST http://localhost:8080/addAnwesenheit
Content-Type: application/json

{
  "awKind": {
    "id": 52
  },
  "awDatum": "2025-03-08",
  "abgeholtUhr": "14:59:59"
}

###GET ALL ANWESENHEITEN
GET http://localhost:8080/anwesenheit
Accept: application/json

###GET ANWENSENHEIT BY KIND
GET http://localhost:8080/getAnwesenheitByKind/52
Accept: application/json

###GET ANWESENHEIT BY DATUM
GET http://localhost:8080/getAnwesenheitByDatum/2025-03-08
Accept: application/json

###UPDATE ANWESENHEIT
PUT http://localhost:8080/updateAnwesenheit/2
Content-Type: application/json

{
  "awKind": {
    "id": 52
  },
  "awDatum": "2025-03-08",
  "abgeholtUhr": "15:59:59"
}

###DELETE ANWESENHEIT
DELETE http://localhost:8080/deleteAnwesenheit/1
Content-Type: application/json